### ISSUE TITLE
Ital axis

### ISSUE THREAD

**Issue by RosaWagner** [displaay/Azeret#1]
Hi
Right now GF is not supporting the slant axis. In order to make an italic appear, we need it separated from the Roman (ie. 2 sources, 2 VF). But it means you won't have an axis to make to slope vary.

If you want this slant variation, then you need to call it slant (slnt) and follow the open-type spec in that regard (negative value). The downside is that you won't have a proper style-linked italic. Since we haven't stated on a fallback name (oblique, LeftLeaning…), there is a chance that the font doesn't get onboarded until further decision.

Cf this issue where we are still trying to figure out a solution for a slant axis: https://github.com/googlefonts/gftools/issues/295#issuecomment-824744342

What do you prefer?

**Comment by displaay** [comment]
I see. We will discuss this with Jan. 
Thank you
Martin

**Comment by RosaWagner** [comment]
@displaay have you come to a decision yet?

**Comment by displaay** [comment]
Yes, we have uploaded separated gx files yesterday (uprights/itslics). Could not find any email address so I wasnt sure how to contact you. Let us know if anything else. 

Best Martin Vacha
+420 608 450 545

**Comment by RosaWagner** [comment]
Ok, don't touch the repo anymore, I'll take it from here. Expect a Pull Request soon with corrections.
